"""empty message

Revision ID: 9b4b768c56
Revises: 5374f37be2e2
Create Date: 2015-04-26 23:55:19.975047

"""

# revision identifiers, used by Alembic.
revision = '9b4b768c56'
down_revision = '5374f37be2e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
